package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IGeneralPlayerStatsRepository;
import dao.uow.IUnitOfWork;
import domain.model.GeneralPlayerStats;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * @author L on 13.11.2016.
 */

public class GeneralPlayerStatsRepository extends RepositoryBase<GeneralPlayerStats> implements IGeneralPlayerStatsRepository {


    private PreparedStatement getKills;
    private PreparedStatement getDeaths;
    private PreparedStatement getRatio;


    public GeneralPlayerStatsRepository(Connection connection, IMapResultSetIntoEntity<GeneralPlayerStats> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

        try {
            getKills = connection.prepareStatement(getKillsSql());
            getDeaths = connection.prepareStatement(getDeathsSql());
            getRatio = connection.prepareCall(getRatioSql());
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


    protected String getKillsSql() {
        return "SELECT * FROM PLAYER_STATS where kills=?";
    }

    protected String getDeathsSql() {
        return "SELECT * FROM PLAYER_STATS where deaths=?";
    }

    protected String getRatioSql() {
        return "SELECT * FROM PLAYER_STATS where ratio=?";
    }



    @Override
    public List<GeneralPlayerStats> kills(int kills) {
        return searchBy(kills, getKills);
    }

    @Override
    public List<GeneralPlayerStats> deaths(int deaths) {
        return searchBy(deaths, getDeaths);
    }

    @Override
    public List<GeneralPlayerStats> ratio(double ratio) {
        List<GeneralPlayerStats> playerRatio = new ArrayList<>();
        try {
            getRatio.setDouble(1, ratio);
            ResultSet resultSet = getKills.executeQuery();
            while (resultSet.next()) {
                playerRatio.add(mapper.map(resultSet));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return playerRatio;
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO PLAYER_STATS(kills, deaths, ratio) values (?, ?, ?)";
    }

    @Override
    public String updateSql() {
        return "UPDATE PLAYER_STATS SET (kills, deaths, ratio)=(?,?,?) where id=?";
    }

    @Override
    protected void setUpdate(GeneralPlayerStats generalPlayerStats) throws SQLException {
        update.setInt(1, generalPlayerStats.getKills());
        update.setInt(2, generalPlayerStats.getDeaths());
        update.setDouble(3, generalPlayerStats.getRatio());
    }

    @Override
    protected void setInsert(GeneralPlayerStats generalPlayerStats) throws SQLException {
        insert.setInt(1, generalPlayerStats.getKills());
        insert.setInt(2, generalPlayerStats.getDeaths());
        insert.setDouble(3, generalPlayerStats.getRatio());
    }


    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE PLAYER_STATS("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "kills int,"
                + "deaths int,"
                + "ratio double" + ")";
    }

    @Override
    protected String tableName() {
        return "PLAYER_STATS";
    }
}
