package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IGeneralTeamStatsRepository;
import dao.uow.IUnitOfWork;
import domain.model.GeneralTeamStats;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/**
 * @author L on 13.11.2016.
 */
public class GeneralTeamStatsRepository extends RepositoryBase<GeneralTeamStats> implements IGeneralTeamStatsRepository {

    public GeneralTeamStatsRepository(Connection connection, IMapResultSetIntoEntity<GeneralTeamStats> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    public List<GeneralTeamStats> withWins(int wins) {
        return null;
    }

    @Override
    public List<GeneralTeamStats> withLooses(int looses) {
        return null;
    }

    @Override
    public List<GeneralTeamStats> withDraws(int draws) {
        return null;
    }

    @Override
    public List<GeneralTeamStats> withPoints(double points) {
        return null;
    }

    protected String insertSql() {
        return "INSERT INTO TEAM_STATS(wins, looses, draws, points) values (?, ?, ?, ?)";
    }

    protected String updateSql() {
        return "UPDATE TEAM_STATS SET (wins,looses,draws,points) = (?,?,?,?) where id=?";
    }

    protected void setUpdate(GeneralTeamStats generalTeamStats) throws SQLException {
        update.setInt(1, generalTeamStats.getWins());
        update.setInt(2, generalTeamStats.getLooses());
        update.setInt(3, generalTeamStats.getDraws());
        update.setDouble(4, generalTeamStats.getPoints());
    }

    protected void setInsert(GeneralTeamStats generalTeamStats) throws SQLException {
        insert.setInt(1, generalTeamStats.getWins());
        insert.setInt(2, generalTeamStats.getLooses());
        insert.setInt(3, generalTeamStats.getDraws());
        insert.setDouble(4, generalTeamStats.getPoints());
    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE TEAM_STATS("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "wins int,"
                + "looses int,"
                + "draws int,"
                + "points double" + ")";
    }

    @Override
    protected String tableName() {
        return "TEAM_STATS";
    }
}
