package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IGeneralPlayerStatsRepository;
import dao.uow.IUnitOfWork;
import domain.model.GeneralPlayerStats;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/**
 * @author L on 13.11.2016.
 */

public class GeneralPlayerStatsRepository extends RepositoryBase<GeneralPlayerStats> implements IGeneralPlayerStatsRepository {

    public GeneralPlayerStatsRepository(Connection connection, IMapResultSetIntoEntity<GeneralPlayerStats> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    public List<GeneralPlayerStats> kills(int kills) {
        return null;
    }

    @Override
    public List<GeneralPlayerStats> deaths(int deaths) {
        return null;
    }

    @Override
    public List<GeneralPlayerStats> ratio(double ratio) {
        return null;
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO PLAYER_STATS(kills, deaths, ratio) values (?, ?, ?)";
    }

    @Override
    public String updateSql() {
        return "UPDATE PLAYER_STATS SET (kills, deaths, ratio)=(?,?,?) where id=?";
    }

    @Override
    protected void setUpdate(GeneralPlayerStats generalPlayerStats) throws SQLException {
        update.setInt(1, generalPlayerStats.getKills());
        update.setInt(2, generalPlayerStats.getDeaths());
        update.setDouble(3, generalPlayerStats.getRatio());
    }

    @Override
    protected void setInsert(GeneralPlayerStats generalPlayerStats) throws SQLException {
        insert.setInt(1, generalPlayerStats.getKills());
        insert.setInt(2, generalPlayerStats.getDeaths());
        insert.setDouble(3, generalPlayerStats.getRatio());
    }


    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE PLAYER_STATS("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "kills int,"
                + "deaths int,"
                + "ratio double" + ")";
    }

    @Override
    protected String tableName() {
        return "PLAYER_STATS";
    }
}
