package dao;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.HistoryOfMatch;

import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;

/**
 * @author L on 13.11.2016.
 */
public class HistoryOfMatchRepository extends RepositoryBase<HistoryOfMatch> {


    public HistoryOfMatchRepository(Connection connection, IMapResultSetIntoEntity<HistoryOfMatch> mapper) {
        super(connection, mapper);
    }


    @Override
    protected String insertSql() {
        return "INSERT INTO HISTORY_OF_MATCH(scoreOfTeam1, scoreOfTeam2, timeOfMatch, TEAM_1_ID," +
                " TEAM_2_ID, MAP_ID, SCOREBOARD_ID) values (?, ?, ?, ?, ?, ?, ?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE HISTORY_OF_MATCH SET (scoreOfTeam1, scoreOfTeam2, timeOfMatch, TEAM_1_ID, TEAM_2_ID" +
                ", MAP_ID, SCOREBOARD_ID)=(?,?,?,?,?,?,?) where id=?";
    }

    @Override
    protected void setUpdate(HistoryOfMatch historyOfMatch) throws SQLException {
        update.setInt(1, historyOfMatch.getScoreOfTeam1());
        update.setInt(2, historyOfMatch.getScoreOfTeam2());
        update.setDate(3, (Date) historyOfMatch.getTimeOfMatch());
        update.setInt(4, historyOfMatch.getTeam1().getId());
        update.setInt(5, historyOfMatch.getTeam1().getId());
        update.setInt(6, historyOfMatch.getMapId());
        update.setInt(7, historyOfMatch.getScoreBoard().getId());
    }

    @Override
    protected void setInsert(HistoryOfMatch historyOfMatch) throws SQLException {
        insert.setInt(1, historyOfMatch.getScoreOfTeam1());
        insert.setInt(2, historyOfMatch.getScoreOfTeam2());
        insert.setDate(3, (Date) historyOfMatch.getTimeOfMatch());
        insert.setInt(4, historyOfMatch.getTeam1().getId());
        insert.setInt(5, historyOfMatch.getTeam2().getId());
        insert.setInt(6, historyOfMatch.getMapId());
        insert.setInt(7, historyOfMatch.getScoreBoard().getId());
    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE HISTORY_OF_MATCH("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "scoreOfTeam1 int,"
                + "scoreOfTeam2 int,"
                + "timeOfMatch date,"
                + "TEAM_1_ID int,"
                + "TEAM_2_ID int,"
                + "MAP_ID int,"
                + "SCOREBOARD_ID int,"
                + "FOREIGN KEY (TEAM_1_ID) REFERENCES TEAM(id),"
                + "FOREIGN KEY (TEAM_2_ID) REFERENCES TEAM(id),"
                + "FOREIGN KEY (MAP_ID) REFERENCES MAPS(id),"
                + "FOREIGN KEY (SCOREBOARD_ID) REFERENCES SCOREBOARD(id)"
                + ")";
    }

    @Override
    protected String tableName() {
        return "HISTORY_OF_MATCH";
    }
}
