package dao;

import java.sql.Connection;

/**
 * Created by L on 13.11.2016.
 */
public class HistoryOfMatchRepository extends RepositoryBase {

    public HistoryOfMatchRepository(Connection connection) {
        super(connection);
    }


    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE HISTORYOFMATCH("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "scoreOfTeam1 int,"
                + "scoreOfTeam2 int,"
                + "timeOfMatch DATE,"
                + "TEAM1_NAME_ID int,"
                + "TEAM2_NAME_ID int,"
                + "MAP_ID int,"
                + "SCOREBOARD_ID int,"
                + "FOREIGN KEY (TEAM1_NAME_ID) REFERENCES TEAM(id),"
                + "FOREIGN KEY (TEAM2_NAME_ID) REFERENCES TEAM(id),"
                + "FOREIGN KEY (MAP_ID) REFERENCES MAPS(id),"
                + "FOREIGN KEY (SCOREBOARD_ID) REFERENCES SCOREBOARD(id)" + ")";
    }

    @Override
    protected String tableName() {
        return "HISTORYOFMATCH";
    }
}
