package dao;

import dao.mappers.IMapResultSetIntoEntity;
import domain.model.PlayerStats;

import java.sql.Connection;
import java.sql.SQLException;

/**
 * @author L on 13.11.2016.
 */

public class PlayerStatsRepository extends RepositoryBase<PlayerStats> {

    public PlayerStatsRepository(Connection connection, IMapResultSetIntoEntity<PlayerStats> mapper) {
        super(connection, mapper);

    }

    @Override
    protected String insertSql() {
        return "INSERT INTO PLAYER_STATS(kills, deaths, ratio) values (?, ?, ?)";
    }

    @Override
    public String updateSql() {
        return "UPDATE PLAYER_STATS SET (kills, deaths, ratio)=(?,?,?) where id=?";
    }

    @Override
    protected void setUpdate(PlayerStats playerStats) throws SQLException {
        update.setInt(1, playerStats.getKills());
        update.setInt(2, playerStats.getDeaths());
        update.setDouble(3, playerStats.getRatio());
    }

    @Override
    protected void setInsert(PlayerStats playerStats) throws SQLException {
        insert.setInt(1, playerStats.getKills());
        insert.setInt(2, playerStats.getDeaths());
        insert.setDouble(3, playerStats.getRatio());
    }


    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE PLAYER_STATS("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "kills int,"
                + "deaths int,"
                + "ratio double" + ")";
    }

    @Override
    protected String tableName() {
        return "PLAYER_STATS";
    }
}
