package dao;

import java.sql.Connection;

/**
 * Created by L on 13.11.2016.
 */
public class TeamStatsRepository extends RepositoryBase {

    public TeamStatsRepository(Connection connection) {
        super(connection);
    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE TEAMSTATS("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "wins int,"
                + "looses int,"
                + "draws int,"
                + "points double" + ")";
    }

    @Override
    protected String tableName() {
        return "TEAMSTATS";
    }
}
